#!/usr/bin/env python
import sys
import optparse
from collections import defaultdict
import random

optparser = optparse.OptionParser()
optparser.add_option("-t", "--train", dest="train", default="../data/train/", help="Data filename prefix (default=data)")
optparser.add_option("-s", "--suffix", dest="suffix", default="_train", help="Data filename suffix (default=_train")
optparser.add_option("-i", "--input", dest="input", default="../data/dev/dev_set", help="Name of input file (default=data/dev/dev_set")

(opts, _) = optparser.parse_args()

lang = ['eng', 'fra', 'deu', 'ita', 'spa']
suffix = opts.suffix
train_dir = opts.train
input_file = opts.input

# Train data
dicts = []
totalSeen = defaultdict(float)
for i in xrange(len(lang)):
  total = 0
  temp = {}
  for line in open(train_dir + lang[i] + suffix):
    words = line.strip().split()
    for (i, word) in enumerate(words):  
      if word not in temp:
        temp[word] = defaultdict(float)
      if i == 0:
        temp[word]["$"] += 1   
      else:
        temp[word][words[i - 1]] += 1
      totalSeen[word] += 1

  dicts.append(temp)

for d in dicts:
  for key in d:
      for val in d[key]:
        d[key][val] /= totalSeen[key]

# Classify language
for line in open(input_file):
  words = line.strip().split()
  samples = []
  for d in dicts:
    totalProb = 0
    for (i, word) in enumerate(words):
      if word in d:
        addedProb = 0
        if i == 0:
          addedProb == d[word]["$"]
        else:
          addedProb = d[word][words[i - 1]]
        if addedProb == 0:
          addedProb = 0.001
        totalProb += addedProb
    samples.append(totalProb)

  max_index = samples.index(max(samples))
  if sum(samples) == 0:
    max_index = random.randint(0,4)
  print lang[max_index]




